Fixes #43: Custom rules for local vhosts now work
devilbox/vhost-gen pull request #44
Opened 2020-11-29 23:53 UTC by CameronHall

Local vhost custom rules are no longer ignored

2020-11-30 10:16 UTC, cytopia commented
@CameronHall thanks for this PR.

Can you give me some more details why this should not be working? I've just tried it from `master` branch:

**1. Adjusted `etc/conf.yml` in this repo (added to `custom:` section):**

`etc/conf.yml:`
```yml
...
custom:
  test
...
```
Just to show what has changed:
```bash
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   etc/conf.yml

no changes added to commit (use "git add" and/or "git commit -a")
```
```diff
$ git diff
diff --git a/etc/conf.yml b/etc/conf.yml
index 94f8b75..41139e7 100644
--- a/etc/conf.yml
+++ b/etc/conf.yml
@@ -68,7 +68,7 @@ conf_dir: /etc/nginx/conf.d
 #   custom statement 1
 #   custom statement 2
 custom:
-
+  test

 # Vhost definition
 vhost:
```


**2. Run `vhost-gen` in this repo:**
```shell
./bin/vhost-gen -p /shared -n www.google.de -c etc/conf.yml -t etc/templates/
```

**3. It shows me the custom section being added:**
```nginx
...
    # Status Page
    location ~ /server-status/ {
        stub_status on;
        access_log off;
    }

    # Custom directives
    test
}
```

2020-11-30 10:55 UTC, CameronHall commented
Hey @cytopia,

I appreciate you taking the time to reply and apologies for providing no steps to reproduce and a vague description. 

**Background**
I discovered this while using devilbox/docker-apache-2.4 and I have only tested the behaviour with the provided `data/vhost-gen/mass.yml` config. I spent a bit of time guessing my way around how this worked exactly, so I won't be surprised if I've just stuffed something up along the way 😄 

**Reproduction**
I've created a short script to reproduce the issue, if you run it from within your vhost-gen project root you should get the same output as me.

```
#!/bin/bash
mkdir tests/resources && curl https://raw.githubusercontent.com/devilbox/docker-apache-2.4/master/data/vhost-gen/mass.yml > tests/resources/mass.yml
echo 'custom: ServerAlias potato.com' > tests/resources/apache24.yml
bin/vhost-gen -n dog.com -c tests/resources/mass.yml -o tests/resources -p /web -t etc/templates
```

**Output before changes**
```xml
    ...
    # Deny Definition
    <FilesMatch "/\.ht.*">
        Order allow,deny
        Deny from all
    </FilesMatch>


    # Custom directives

</VirtualHost>
```

**Output after changes**
```xml
    ...
    # Deny Definition
    <FilesMatch "/\.ht.*">
        Order allow,deny
        Deny from all
    </FilesMatch>


    # Custom directives
    ServerAlias potato.com
</VirtualHost>
```

2020-12-01 10:21 UTC, cytopia commented
I can reproduce this behaviour. Currently still trying to figure out why my example works and yours doesn't

2020-12-03 15:54 UTC, science695 commented
@cytopia I'm not super familiar with yaml syntax, but your example has the custom text on the next line down, while his example is inline.

Could that be the issue?

2020-12-03 16:00 UTC, cytopia commented
> @cytopia I'm not super familiar with yaml syntax, but your example has the custom text on the next line down, while his example is inline.
> 
> Could that be the issue?

Changed it to:
```yaml
custom: |
  test
```
and
```yaml
custom: test
```
which works for me.

The issue is rather with `-o` (override) as seen in @CameronHall example

2020-12-05 09:29 UTC, cytopia commented
**FYI-Update:**  @CameronHall 

Currently adding full debug output to `vhost-gen`. It already seems, that your custom definition should go into the configuration file, not the template:


```bash
$ bin/vhost-gen -n dog.com -c tests/resources/mass.yml -o tests/resources -p /web -t etc/templates -vv >/dev/null
vhost-gen: [INFO]  (2020-12-05 10:21:40): Loading configuration file        (-c): tests/resources/mass.yml
vhost-gen: [INFO]  (2020-12-05 10:21:40): Loading vhost template (global)   (-t): etc/templates/apache24.yml
vhost-gen: [INFO]  (2020-12-05 10:21:40): Loading vhost template (override) (-o): tests/resources/apache24.yml
vhost-gen: [INFO]  (2020-12-05 10:21:40): Creating vhost type: http-only (plain)
vhost-gen: [DEBUG] (2020-12-05 10:21:40): [status] Retrieving cfg 'enable': False
vhost-gen: [DEBUG] (2020-12-05 10:21:40): [status] Returning:
vhost-gen: [DEBUG] (2020-12-05 10:21:40): [custom] Retrieving cfg 'custom':
vhost-gen: [DEBUG] (2020-12-05 10:21:40): [custom] Returning': None
vhost-gen: [INFO]  (2020-12-05 10:21:40): Using vhost name: dog.com__TLD__
```

The templates should not be modified, as they already contain all required server-specific configuration sections. The config file itself is used to replace values into the templates.
In your case, you are trying to hardcode values in the template. this should however go into `tests/resources/mass.yml` instead.

You've probably mixed up template and config?

2020-12-05 10:03 UTC, cytopia commented
@CameronHall have a look at this version (not complete yet, but with `-vvv` you can see what exactly it is doing)

https://github.com/devilbox/vhost-gen/pull/45

2020-12-06 11:54 UTC, CameronHall commented
@cytopia my specific use case for this was to add a `ServerAlias` to virtual hosts for two independent projects in [devilbox/docker-apache-2.4](https://github.com/devilbox/docker-apache-2.4) where the aliases vary between projects. The command I provided is a slight variation of [this](https://github.com/devilbox/docker-apache-2.4/blob/master/data/create-vhost.sh#L33).
 
I understand what you're saying with respect to hardcoding values, but I think the override should be considered "extra vhost configuration"? Instead of a "template override". That's just my opinion for this specific use case, I don't any exposure to using this tool outside of my own use cases - so I'd appreciate your perspective 😄

2020-12-06 12:06 UTC, cytopia requested changes

2020-12-06 12:06 UTC, cytopia commented on bin/vhost-gen
> +            "__PHP_FPM__": str_indent(vhost_get_php_fpm(config, tpl, docroot, proxy), 4),
```suggestion
            "__PHP_FPM__": str_indent(vhost_get_php_fpm(config, tpl, docroot, proxy, verbose), 4),
```

2020-12-06 12:06 UTC, cytopia commented on bin/vhost-gen
> +            "__ALIASES__": str_indent(vhost_get_aliases(config, tpl), 4),
```suggestion
            "__ALIASES__": str_indent(vhost_get_aliases(config, tpl, verbose), 4),
```

2020-12-06 12:06 UTC, cytopia commented on bin/vhost-gen
> +            "__DENIES__": str_indent(vhost_get_denies(config, tpl), 4),
```suggestion
            "__DENIES__": str_indent(vhost_get_denies(config, tpl, verbose), 4),
```

2020-12-06 12:06 UTC, cytopia commented on bin/vhost-gen
> +            "__SERVER_STATUS__": str_indent(vhost_get_server_status(config, tpl), 4),
```suggestion
            "__SERVER_STATUS__": str_indent(vhost_get_server_status(config, tpl, verbose), 4),
```

2020-12-06 12:06 UTC, cytopia commented on bin/vhost-gen
> +            "__CUSTOM__": str_indent(vhost_get_custom_section(config, tpl), 4),
```suggestion
            "__CUSTOM__": str_indent(vhost_get_custom_section(config, tpl, verbose), 4),
```

2020-12-06 12:06 UTC, cytopia commented on bin/vhost-gen
>      log(3, "[custom]  Returning': {}".format(output), verbose)
This should be right above the return statemt to see the final return value

2020-12-06 12:10 UTC, cytopia commented on bin/vhost-gen
> +def vhost_get_custom_section(config, template, verbose):
```suggestion
def vhost_get_custom_section(config, template, verbose):
    # type: (Dict[str, Any], Dict[str, Any], int) -> str
```

2020-12-06 12:16 UTC, cytopia requested changes

2020-12-06 12:16 UTC, cytopia commented on bin/vhost-gen
>      log(3, "[custom]  Retrieving cfg 'custom': {}".format(output), verbose)
This was one too much. The first log statement is about what has been retrieved from the config, so this should be directory below the first `output = to_str(config["custom"])` line

2020-12-06 12:16 UTC, cytopia commented on bin/vhost-gen
>      log(3, "[custom]  Retrieving cfg 'custom': {}".format(output), verbose)
```suggestion
```

2020-12-06 12:16 UTC, cytopia commented on bin/vhost-gen
>      output = to_str(config["custom"])
```suggestion
    output = to_str(config["custom"])
    log(3, "[custom]  Retrieving cfg 'custom': {}".format(output), verbose)
```

2020-12-06 12:16 UTC, cytopia commented on bin/vhost-gen
> +
```suggestion
```

2020-12-06 12:19 UTC, cytopia reviewed
Can you bump the version to:

`bin/vhost-gen`
```diff
- VERSION = "1.0.2"
+ VERSION = "1.0.3"
```

`setup.py`
```diff
-    version="1.0.2",
+    version="1.0.3",
```

2020-12-06 12:22 UTC, CameronHall commented
The version number has been bumped

2020-12-06 12:23 UTC, cytopia approved these changes
Doesn't hurt to have this feature :-) Thanks for the contribution :+1:

2020-12-06 12:36 UTC, merged

2020-12-06 12:38 UTC, cytopia commented
Available via pip now: https://pypi.org/project/vhost-gen/